apiVersion: v1
kind: Secret
metadata:
  name: fabflix-db-credentials
type: Opaque
data:
  # username: echo -n 'mytestuser' | base64  =>  bXl0ZXN0dXNlcg==
  DB_USER: bXl0ZXN0dXNlcg==
  # password: echo -n 'My6$Password' | base64 =>  TXk2JFBhc3N3b3Jk
  DB_PASSWORD: TXk2JFBhc3N3b3Jk